trigger:
  branches:
    include:
      - main
      - releases/*
  paths:
    exclude:
      - ./README.md
      - ./docker-compose.yml

resources:
  containers:
    - container: agent
      image: nguyenkhacthanh/container-pipeline:latest
      options: --privileged
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock

variables: 
  - name: image_tag
    value: ''
  - name: docker_repo
    value: 'courtapps/frontend'
  - name: docker_registry
    value: '269372837096.dkr.ecr.ap-southeast-2.amazonaws.com'
  - name: aws_region
    value: 'ap-southeast-2'

container: agent

steps:
  - bash: |
      image_tag=$(echo "$(Build.SourceBranch)" | cut -d'/' -f2)
      echo "##vso[task.setvariable variable=image_tag]$image_tag"
    condition: startsWith(variables['Build.SourceBranchName'], 'releases/')
    displayName: 'Image tag as branch name'

  - script: |
      image_tag=$(echo $(Build.SourceVersion) | cut -c1-8)
      echo "image_tag: $image_tag"
      echo "##vso[task.setvariable variable=image_tag]$image_tag"
    displayName: 'Image tag as commit ID'
    condition: eq(variables['Build.SourceBranchName'], 'main')

  - bash: |
      docker build . -t $(docker_registry)/$(docker_repo):$(image_tag) --build-arg IMAGE_TAG=$(image_tag)
    displayName: 'Build image'

  - bash: |
      export AWS_ACCESS_KEY_ID=$(aws_access_key_id)
      export AWS_SECRET_ACCESS_KEY=$(aws_secret_access_key)
      aws ecr get-login-password --region $(aws_region) | docker login --username AWS --password-stdin $(docker_registry)
    displayName: 'Docker login'

  - bash: |
      docker tag $(docker_registry)/$(docker_repo):$(image_tag) $(docker_registry)/$(docker_repo):latest
      docker push $(docker_registry)/$(docker_repo):latest
      docker push $(docker_registry)/$(docker_repo):$(image_tag)
    displayName: 'Push image'


